package simulation.resource;

public enum Resource_Type {

	PARKING_SPOT_AVAILABLE_AND_RESERVED,
	PARKING_SPOT_AVAILABLE_AND_NOT_RESERVED,
	CLEANING_SPOT,
	EMPLOYEE_ASSISTANT,
	EMPLOYEE_CLEANER,
	CASH_REGISTER
	
}
